packages:
  - src/apps/*
  - src/packages/*
  - src/modules/*
  - coordination

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@temporalio/core-bridge'
  - bcrypt
  - msgpackr-extract
  - prisma
  - protobufjs
