
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nest-ddd-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nest-ddd-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nest-ddd-chart.name" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"
