version: '3.8'
services:
  db-test:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - '5433:5432'
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis-test:
    image: redis:7
    ports:
      - '6380:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  app-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      DATABASE_URL: postgresql://test:test@db-test:5432/test
      REDIS_URL: redis://redis-test:6379
      JWT_SECRET: test-secret
      NODE_ENV: test
    ports:
      - '3001:3000'
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    command: >
      sh -c "
        pnpm prisma:generate &&
        pnpm prisma migrate deploy &&
        pnpm test:e2e:full
      "

volumes:
  test-db-data: