
name: CD
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      - name: Helm Deploy
        uses: deliverybot/helm@v2
        with:
          args: upgrade --install nest-ddd ./helm/nest-ddd-chart -f ./helm/nest-ddd-chart/values.yaml --wait --timeout=10m
        continue-on-error: false
      - name: Notify on failure
        if: failure()
        run: |
          echo "Deployment failed. Check logs for details."
          # Add notification logic here (Slack, email, etc.)
